[package]
name = "phoenix-rs-orb-rust"
description = "Sample rust project used to validate orb functionality"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
