version: 2.1
orbs:
  rust: phoenix-rs/rust@dev:<<pipeline.git.revision>>
  orb-tools: circleci/orb-tools@11.1

filters: &filters
  tags:
    only: /.*/

executors:
  custom-docker:
    docker:
      - image: cimg/rust:1.65
  custom-docker-norust:
    docker:
      - image: cimg/base:current-22.04

workflows:
  test-deploy:
    jobs:
      # Make sure to include "filters: *filters" in every test job you want to run as part of your deployment.
      - rust/lint-test-build:
          filters: *filters
          name: test-builtin-default-executor
          store_artifact: true
          artifact_destination: testapp-builtin
      - rust/lint-test-build:
          filters: *filters
          name: test-builtin-other-executor
          target: rust/linux-arm64
          store_artifact: true
          artifact_destination: testapp-builtin-arm64
      - rust/lint-test-build:
          filters: *filters
          name: test-exernal-executor
          target: custom-docker
          target_setup: false
          store_artifact: true
          artifact_destination: testapp-external
      - rust/lint-test-build:
          filters: *filters
          name: test-exernal-executor-norust
          target: custom-docker-norust
          store_artifact: true
          artifact_destination: testapp-external

      - orb-tools/pack:
          filters: *filters

      - orb-tools/publish:
          orb-name: phoenix-rs/rust
          vcs-type: << pipeline.project.type >>
          pub-type: production
          requires:
            - orb-tools/pack
            - test-builtin-default-executor
            - test-builtin-other-executor
            - test-exernal-executor
            - test-exernal-executor-norust
          context: orb-publishing
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v[0-9]+\.[0-9]+\.[0-9]+$/
